### ISSUE TITLE
Flatpak release?

### ISSUE THREAD

**Issue by tominglis** [trelby/trelby#12]
It would be great to have this available as a Flatpak! I am very happy to help test it.

**Comment by gwowen** [comment]
Sadly I think this project is a bit dead. I found a Python 3 version someone made here that might have one? https://github.com/limburgher/trelby

**Comment by UnisTorvalds** [comment]
Definitely use limburgher's fork.  This branch has been unmaintained for years.

**Comment by janopae** [comment]
I'm working on a Flatpak for the fork in https://github.com/limburgher/trelby/pull/79 btw.

**Comment by ttang4299** [comment]
@janopae Hope to see it published to Flathub when it's ready!

**Comment by ttang4299** [comment]
Hi @janopae , just wondering if you had any updates on a potential Flatpak release, since the limburgher fork was merged to the main project.

**Comment by priframr** [comment]
What is the current status on this? I don't mind packaging it up for flathub, I won't have time to maintain it, but I can put together the build recipe for you and post it here.

**Comment by priframr** [comment]
I don't know whom to ping for this (I think @limburgher is a prominent contributor to this repo), but I finally got a working flatpak recipe created. It works. Now, it should next be submitted to flathub by making a PR to the [flathub github repo](https://github.com/flathub/flathub). Also, this is missing a few components like the xml file for the appstores to read, but it builds and that is what I was aiming for.

Ensure you have the flatpak-builder program setup and I used a python convenience script to make the pip deps JSON file from [here](https://github.com/flatpak/flatpak-builder-tools/tree/master/pip). Then on the command line, type the following when in the directory where the yaml script is:
`flatpak-builder --force-clean --user --install-deps-from=flathub --repo=repo --install builddir com.trelby.Trelby.yaml`

And you should get a completed install. I have attached here my recipe, if this gets into flathub, just imagine it: trelby could possibly get stuff like scene or page locking from more contributors wanting to contribute. The possibilities are endless.

[Archive.zip](https://github.com/user-attachments/files/17003478/Archive.zip)

**Comment by priframr** [comment]
> I'm working on a Flatpak for the fork in [limburgher#79](https://github.com/limburgher/trelby/pull/79) btw.

Are you still working on a new flatpak release? I think I got the ball rolling for a flathub build.

**Comment by limburgher** [comment]
Not personally but I welcome the assistance!

**Comment by priframr** [comment]
It's done.
https://flathub.org/apps/org.trelby.Trelby
@limburgher can close this now.
Give it a bit of time for the website to update.

**Comment by limburgher** [comment]
org.trelby.Trelby is now on Flathub.

**Comment by ttang4299** [comment]
@limburgher Thank you so much, looking forward to making movies on my little gaming handheld
