### ISSUE TITLE
On going maintenance?

### ISSUE THREAD

**Issue by agray** [trelby/trelby#2]
Is this code base being maintained anymore?

If not, is there another free tool that is?

**Comment by petterreinholdtsen** [comment]
Good question.  I was wondering if it should become part of the Debian distribution, but lack of response here seem a little scary.

Perhaps one of the forks on https://github.com/trelby/trelby/network/ or https://github.com/oskusalerma/trelby/network are being maintained?

**Comment by anilgulecha** [comment]
Hi,

Trelby is considered largely complete-ware, with no feature changes
planned. We have to cut a release with latest master, and some PRs that are
good to go, but have not gotten around to it.

**Comment by agray** [comment]
Looking forward to the new release

There is always opportunity for innovation in the form of feature additions
and bug fixes.

Suggest nothing is ever complete.

On Windows 10 Trelby latest release will often freeze requiring process
kill and restart with attendant loss of unsaved work.

Regards,

Andrew

**Comment by petterreinholdtsen** [comment]
I notice from <URL: https://bugs.debian.org/669068 > there was some
effort a few years ago to make the source code and application layout
according to the Debian requirements.  Do you know if this work was
completed?

Is there any interest in having the program as part of the Debian
archive?  I could help, as I got upload rights to Debian.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by limburgher** [comment]
FYI I have a PR open for a port to Python 3, and I'm maintaining it at https://github.com/limburgher/trelby
