### ISSUE TITLE
Requesting permission for flathub build

### ISSUE THREAD

**Issue by priframr** [trelby/trelby#26]
I have submitted a PR for flathub merge, it builds and lints correctly on my machine. I just need to ask for your permission as well as I would like to ask someone here to be the official maintainer for updates because I won't have time to update it myself. You can find the PR here:
https://github.com/flathub/flathub/pull/5597

**Comment by limburgher** [comment]
Yes, I can handle updates, thank you! What do I need to do to facilitate that? I've only ever worked on flatpaks within Fedora, not on flathub.

**Comment by priframr** [comment]
> Yes, I can handle updates, thank you! What do I need to do to facilitate that? I've only ever worked on flatpaks within Fedora, not on flathub.

Flathub uses a buildbot system for building, you'll be added to the git repos maintainers permission and can modify the yaml scripts among others. I had to add in a patch for making flatpak work better with trelby, any questions you can ask in the linked repo. Lets please keep this current issue open until the PR is merged.

**Comment by priframr** [comment]
The flatpak merge is complete. Closing this issue now.

**Comment by ttang4299** [comment]
Awesome, how much longer before it appears in the repo @priframr ? I've got KDE Discover on standby for install (really looking to get this thing on my Steam Deck so I can start typing scripts on the go)

**Comment by priframr** [comment]
> Awesome, how much longer before it appears in the repo @priframr ? I've got KDE Discover on standby for install (really looking to get this thing on my Steam Deck so I can start typing scripts on the go)

It got merged about 4 hours ago, so I say not much longer. 3-4ish (going by a guess) more hours until it's ready to be used on app stores. It's not by design an instant update, it takes a matter of hours to publish.

**Comment by priframr** [comment]
@ttang4299 
Does steam deck even allow for pacman usage beyond steam games? I don't own a steam deck, so I have no idea.

**Comment by ttang4299** [comment]
@priframr There's a Desktop Mode where I have desktop apps installed. Valve intentionally left it open so users could install apps like Discord and/or outside game launchers which Steam could then add shortcuts to in Gaming Mode if one wanted. I have a Bluetooth keyboard and mouse setup as well as a 3D printed stand, which makes it a handy and secure substitute for a laptop.

**Comment by priframr** [comment]
> @priframr There's a Desktop Mode where I have desktop apps installed. Valve intentionally left it open so users could install apps like Discord and/or outside game launchers which Steam could then add shortcuts to in Gaming Mode if one wanted. I have a Bluetooth keyboard and mouse setup as well as a 3D printed stand, which makes it a handy and secure substitute for a laptop.

Hi. It's up and running. I don't know if you know yet, just wanted to inform you that you can install it now via KDE Discover.

**Comment by ttang4299** [comment]
@priframr Got it up and running now!
