### ISSUE TITLE
The "Save to" option does not work in the Main Settings and Script Settings

### ISSUE THREAD

**Issue by rcentros** [trelby/trelby#28]
Not a high priority, but I thought I would request this anyhow. 

In the Settings sub-menus, in both the File and Script Menus, you can **Load** or **Change**, but you can't **Save As** (nothing happens). This means you can't make changes to the theme (in the File Menu) and save them, or changes to Script format (in the Script Menu) and save those changes for future Loading. My workaround at this point is to use an old computer that can still run Trelby 2.3 (I believe, or maybe 2.2), create the themes there, save them and then and copy these to the new computer. It would be nice if this **Save As** Menu worked.

As I say, not a high priority.

**Comment by limburgher** [comment]
This was actually an easy fix. It's fixed in master, and will be in the next release.

**Comment by rcentros** [comment]
That's great. Thank you!
