### ISSUE TITLE
Backwards-compatiblity for Latin1 characters in the .trelby file format might be broken

### ISSUE THREAD

**Issue by janopae** [trelby/trelby#37]
Historically, .trelby files were encoded in Latin1 (according to https://github.com/trelby/trelby/issues/32#issuecomment-2376671127). Python 3 changed the encoding of all strings to UTF 8.

I don't think we ever took care of converting them to Latin1 when writing files. In fact, we can write Non-Latin1 characters nowadays. Therefore, I assume, that Trelby nowadays writes (and reads) files assuming they are UTF 8.

This would mean that opening older Trelby files with Latin1 characters should be broken now (and that newer files should be broken in older versions of the program if they use non-ASCII characters).

I think we should check if this is actually the case, and if yes, introduce a new version number of the trelby file format. When loading a trelby file, only if the file version is new enoough it should be treated as UTF 8 – else, it should be converted from Latin1, so old files with Latin1 characters can still be viewed. When saving, we might just convert the file to UTF 8 and rewrite the version string.

**Comment by limburgher** [comment]
I'm fairly certain that my changes to move to Python 3 took this into account. Specifically see src/util.py 912-918.

**Comment by janopae** [comment]
> I'm fairly certain that my changes to move to Python 3 took this into account. Specifically see src/util.py 912-918.

That's exactly what I mean.

https://github.com/trelby/trelby/blob/6f5ec0ebf9e86f53bff0d99c688c4a7fcc793302/src/util.py#L914

This line decodes files, assuming they are in UTF-8.

In case it is true that historically, .trelby files have been in Latin1 (which is what [this comment](https://github.com/trelby/trelby/issues/32#issuecomment-2376671127) by @anilgulecha suggests), then this would be a breaking change.

However, looking back at the code history, it seems like files have been decoded as UTF-8 even in the Python 2 days. So maybe, Trelby has always saved files in UTF-8 and we don't even have a problem here?

**Comment by janopae** [comment]
I just saved a file with the Windows version of Trelby 2.2 downloaded from https://www.trelby.org/download/.

I can confirm that the mime type of the file is UTF-8 and it indeed seems to be encoded in UTF-8.

@anilgulecha Was there any point in time where .trelby files have not been in UTF-8 (like your comment suggests, "lines were made of latin-1 characters"), or was that a mistake?

**Comment by anilgulecha** [comment]
My bad for earlier. File encoding would be UTF8. Application support itself was for for latin-1 charset.

**Comment by janopae** [comment]
Thanks! That means we don't have an issue here.
