### ISSUE TITLE
Name database and spell checker not working in 2.4.10 flathub version

### ISSUE THREAD

**Issue by rcentros** [trelby/trelby#38]
I normally use the .deb packaged version of Trelby, so didn't realize until now that the spelling checker and name database are not loading in the Flatpak version of Trelby 2.4.10.

I'm getting these errors (tried on more than one computer in Linux Mint 22 and 21.3). 

`Error loading file 'names.txt.gz': Decompression failed`

And...

`Error loading file 'dict_en.dat.gz': Decompression failed`

I don't know where Flatpak stores these files or I would try to troubleshoot this issue.

**Comment by limburgher** [comment]
This is because the source tarball used in the flatpak is source only, and needs "make" run to generate those two files. Apparently the user that set up the initial flatpak has deleted their account...

**Comment by janopae** [comment]
I had a Flatpak script working in https://github.com/limburgher/trelby/pull/79.

I wanted to focus on creating a nightly build first, before submitting anything to Flathub that anyone would consider stable.

The problems this PR had were largely how to split up the Makefile tasks in a user-friendly way, while getting flatpak to install the thing without being in a repository.

On Flathub, we don't have any of these problems, so someone might want to use this PR as a basis for a working Flathub version.

**Comment by limburgher** [comment]
Thank you @janopae! I used what I learned from your PR and what was put in Flatpak, and a fixed build is coming to Flathub.  I've also learned a LOT about flatpaks in the process, and I have an idea what I need to do to modernize the overall Trelby packaging.
