### ISSUE TITLE
2.4.11 does not run

### ISSUE THREAD

**Issue by txtsd** [trelby/trelby#46]
Now that this project is PEP517 compliant, I've used the [recommended method](https://wiki.archlinux.org/title/Python_package_guidelines#Standards_based_(PEP_517)) to install python packages on Arch.

It installs to `/usr/lib/python3.12/site-packages/trelby`, however:

```
❯ python /usr/lib/python3.12/site-packages/trelby/trelby.py
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/trelby/trelby.py", line 3, in <module>
    import trelby
  File "/usr/lib/python3.12/site-packages/trelby/trelby.py", line 4, in <module>
    from trelby.error import TrelbyError
ModuleNotFoundError: No module named 'trelby.error'; 'trelby' is not a package
```

**Comment by txtsd** [comment]
And if I install the `trelby.py` from the root dir into `/opt` and launch it that way:

```
❯ /opt/trelby/trelby.py
Traceback (most recent call last):
  File "/opt/trelby/trelby.py", line 4, in <module>
    import trelby.trelby
  File "/opt/trelby/trelby.py", line 4, in <module>
    import trelby.trelby
ModuleNotFoundError: No module named 'trelby.trelby'; 'trelby' is not a package
```

**Comment by limburgher** [comment]
Installing from pip should result in an entry point script called 'trelby' in /usr/bin or the like. Does it not?

**Comment by txtsd** [comment]
> Installing from pip should result in an entry point script called 'trelby' in /usr/bin or the like. Does it not?

It actually does, and I was overwriting it :expressionless:

Thanks!

**Comment by limburgher** [comment]
Excellent!
