### ISSUE TITLE
BUG: Cursor via Mouse Scroll Wheel doesn't transition to next page  Linux?Deb Version 2.4.1

### ISSUE THREAD

**Issue by JPK1713** [trelby/trelby#50]
Running the Deb version 2.4.1 on Ubuntu

Mouse works perfect on Word docs, browsing, but  in Trelby the scroll wheel won't transition to the next page in either direction. So, I have to  use "page up" or "page down" or the arrows.

Pain in the butt.

Anyone have any information to share?

Tia.

**Comment by rcentros** [comment]
This issue started with 2.4.10. A report was entered [(issue #29)](https://github.com/trelby/trelby/issues/29)

I agree, it's a pain in the butt.

**Comment by limburgher** [comment]
Meant to close this as duplicate.
