### ISSUE TITLE
Follow the XDG Base Dir spec

### ISSUE THREAD

**Issue by Samueru-sama** [trelby/trelby#54]
Trelby creates a `~/.trelby` dir where config files are stored, this should be instead `${XDG_CONFIG_HOME:-$HOME/.config}/trelby`

edit: if the above line isn't clear, the app should check if `XDG_CONFIG_HOME` is set and if so use that location, else default to `$HOME/.config`

Further info: 

https://specifications.freedesktop.org/basedir-spec/latest/
https://wiki.archlinux.org/title/XDG_Base_Directory

**Comment by rcentros** [comment]
I like that the Trelby config files are in the ~/.trelby directory. This makes it easy to group, edit and find my custom Trelby configuration files without "losing" them in a generic configuration directory. With 2.4.11 Trelby is once again able to save .conf and .sconf files, for quick loading of custom colors and formatting features.

I currently have 16 .conf and .sconf files in my ~/.trelby directory.

**Comment by UnisTorvalds** [comment]
We should follow convention and put the config files in the ~/.config directory. It's only one level down.  Breaking convention is counter-intuitive and makes things harder to find.

**Comment by Samueru-sama** [comment]
> I currently have 16 .conf and .sconf files in my ~/.trelby directory.

You would have 16 files on `~/.config/trelby`

A great thing of the XDG Base dir spec is that the locations are env variables, `~/.config` is the default used when `XDG_CONFIG_HOME` isn't set, you can set `XDG_CONFIG_HOME=$HOME` if you don't like having config files one level down, I don't think this is a good idea but you can lol

**Comment by rcentros** [comment]
To UnisTorvalds and Samueru-sama... I get what you're saying now. For some I got it in my head that the Trelby's configuration files would be mixed with a lot of other .config files. This is what I get for writing in the middle of the night. Yes, ~/.config/Trelby makes sense. I don't mind them at ~/.trelby either, but I see your point about consistency. I guess I'm just used to them being in a specific spot.

**Comment by Samueru-sama** [comment]
[Looks like this is where ~/.trelby comes from](https://github.com/trelby/trelby/blob/master/trelby/misc.py#L57).

Something like this would need to be done instead: 

```
xdg_config_home = os.environ.get("XDG_CONFIG_HOME")
if xdg_config_home:
    confPath = os.path.join(xdg_config_home, "trelby")
elif os.path.exists(os.path.join(os.environ["HOME"], ".trelby")):
    confPath = os.path.join(os.environ["HOME"], ".trelby")
else:
    confPath = os.path.join(os.environ["HOME"], ".config", "trelby")
 ```
It checks if `XDG_CONFIG_HOME` is set, if so it will use that + `trelby`. 

If not set it checks if the `~/.trelby` dir exists, if so it uses that instead (this is compatibility with people already using `~/.trelby`). 

If the dir doesn't exist it falls back to `~/.config/trelby`

 *AI was consulted to get the above snipped, I have no idea how to write python, iirc there are xdg libraries for this as well.

**Comment by limburgher** [comment]
Thank you, I'll be fixing this shortly.
